# Generated by Django 4.2.2 on 2023-07-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyusage',
            table='daily_usage',
        ),
    ]
