# Generated by Django 4.2.2 on 2023-07-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_monthlyusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyusage',
            old_name='date',
            new_name='month',
        ),
    ]
