# Generated by Django 4.2.2 on 2023-07-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('ec2Price', models.IntegerField()),
                ('ebsPrice', models.IntegerField()),
                ('eksPrice', models.IntegerField()),
                ('esPrice', models.IntegerField()),
                ('rdsPrice', models.IntegerField()),
            ],
            options={
                'db_table': 'resource_price',
            },
        ),
    ]
