# Generated by Django 4.2.2 on 2023-07-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprice',
            name='ebsPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resourceprice',
            name='ec2Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resourceprice',
            name='eksPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resourceprice',
            name='esPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resourceprice',
            name='rdsPrice',
            field=models.FloatField(),
        ),
    ]
